name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: ./source/android
      run: ./gradlew build

    - name: Sign with apksigner
      working-directory: ./source/android
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.KS_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KS_PASS }}
        keyPassword: ${{ secrets.KEY_PASS }}
        signedReleaseFile: app/release
      
    - name: Deploy to Server
      working-directory: ./source/android/app/release
      run: |
        for file in `find . -name "*.apk" -type f  -print`; do
          file=`readlink -f $file`
          curl -X "POST" -F "file=@$file" ${{ secrets.UPLOAD_URL }}
        done
      
    - name: Publish Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./source/android/app/build/outputs/apk/release/*.apk