name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: ./source/android
      run: ./gradlew build

    - name: Sign with apksigner
      working-directory: ./source/android
      run: |
        unsign_root="./app/build/outputs/apk/release"
        signed_root="./app/release"
        for file in `ls $unsign_root`; do
          filelink=`readlink -f $file`
          unsigned_apk="$filelink"
          aligned_apk="$signed_root/aligned.apk"
          signed_apk=$signed_root/$file

          zipalign -v -p 4 "$unsigned_apk" "$$aligned_apk"
          apksigner sign --v1-signing-enabled true --v2-signing-enabled true --ks "./release.jks" --ks-pass pass:"${{ secrets.KS_PASS }}" --ks-key-alias "${{ secrets.KS_KEY_ALIAS }}" --key-pass pass:"${{ secrets.KEY_PASS }}" --out "$signed_apk" "$aligned_apk"
          apksigner verify --min-sdk-version $min_sdk_version "$signed_apk"
          echo "Signed $file"
        done
      
    - name: Deploy to Server
      working-directory: ./source/android/app/release
      run: |
        for file in `find . -name "*.apk" -type f  -print`; do
          file=`readlink -f $file`
          curl -X "POST" -F "file=@$file" ${{ secrets.UPLOAD_URL }}
        done
      
    - name: Publish Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./source/android/app/build/outputs/apk/release/*.apk