name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: ./source/android
      run: ./gradlew build
      
    - name: Publish Build Artifact
      working-directory: ./source/android/app/build/outputs/apk
      uses: actions/upload-artifact@v2
      with:
        name: android
        path: ./release

    - name: Deploy to Server
      working-directory: ./source/android/app/build/outputs/apk/release
      run: |
        for file in `find . -name "*.apk" -type f  -print`; do
          file=`readlink -f $file`
          curl -X "POST" -F "file=@$file" https://cloud.whoam.xyz/v1/apk
        done